import { FavoriteMovie, SocialActivityItem, SocialUser } from "./types";

export const favoriteMoviesMock: FavoriteMovie[] = [];

export const friendsMock: SocialUser[] = [
  { id: "u-001", username: "cineNora", followersCount: 420, avatarUrl: null },
  { id: "u-002", username: "FrameHunter", followersCount: 290, avatarUrl: null },
  { id: "u-003", username: "SofiCritica", followersCount: 260, avatarUrl: null },
  { id: "u-004", username: "NeoMovies", followersCount: 180, avatarUrl: null },
  { id: "u-005", username: "LunaFilm", followersCount: 160, avatarUrl: null },
  { id: "u-006", username: "OscarScope", followersCount: 120, avatarUrl: null },
];

export const followingMock: SocialUser[] = [
  { id: "u-001", username: "cineNora", followersCount: 420, avatarUrl: null },
  { id: "u-007", username: "RetroPulse", followersCount: 390, avatarUrl: null },
  { id: "u-008", username: "AriVisuals", followersCount: 310, avatarUrl: null },
  { id: "u-009", username: "MovieMint", followersCount: 275, avatarUrl: null },
  { id: "u-003", username: "SofiCritica", followersCount: 260, avatarUrl: null },
  { id: "u-010", username: "ClackDirector", followersCount: 140, avatarUrl: null },
];

export const socialActivityMock: SocialActivityItem[] = [
  {
    id: "act-001",
    tab: "following",
    user: followingMock[0],
    movieTitle: "Blade Runner 2049",
    movieYear: 2017,
    createdAt: "2026-04-08T10:20:00.000Z",
    interactionType: "rating",
    ratingValue: 5,
  },
  {
    id: "act-002",
    tab: "following",
    user: followingMock[1],
    movieTitle: "Perfect Blue",
    movieYear: 1997,
    createdAt: "2026-04-08T09:00:00.000Z",
    interactionType: "comment",
    commentText: "La tensión psicológica está brutal en cada frame.",
  },
  {
    id: "act-003",
    tab: "following",
    user: followingMock[2],
    movieTitle: "Arrival",
    movieYear: 2016,
    createdAt: "2026-04-07T21:15:00.000Z",
    interactionType: "like",
    likedCommentSnippet: "Qué final tan elegante y emotivo.",
  },
  {
    id: "act-004",
    tab: "following",
    user: followingMock[3],
    movieTitle: "Whiplash",
    movieYear: 2014,
    createdAt: "2026-04-07T20:30:00.000Z",
    interactionType: "rating",
    ratingValue: 4,
  },
  {
    id: "act-005",
    tab: "following",
    user: followingMock[4],
    movieTitle: "La La Land",
    movieYear: 2016,
    createdAt: "2026-04-07T20:00:00.000Z",
    interactionType: "comment",
    commentText: "Colorimetría impecable, banda sonora top.",
  },
  {
    id: "act-006",
    tab: "following",
    user: followingMock[0],
    movieTitle: "Interstellar",
    movieYear: 2014,
    createdAt: "2026-04-06T22:00:00.000Z",
    interactionType: "comment",
    commentText: "Cada revisión suma capas nuevas.",
  },
  {
    id: "act-007",
    tab: "friends",
    user: friendsMock[0],
    movieTitle: "Her",
    movieYear: 2013,
    createdAt: "2026-04-08T11:00:00.000Z",
    interactionType: "rating",
    ratingValue: 5,
  },
  {
    id: "act-008",
    tab: "friends",
    user: friendsMock[1],
    movieTitle: "Drive",
    movieYear: 2011,
    createdAt: "2026-04-08T08:30:00.000Z",
    interactionType: "like",
    likedCommentSnippet: "Ryan Gosling transmite todo en silencio.",
  },
  {
    id: "act-009",
    tab: "friends",
    user: friendsMock[2],
    movieTitle: "No Country for Old Men",
    movieYear: 2007,
    createdAt: "2026-04-07T23:00:00.000Z",
    interactionType: "comment",
    commentText: "Seco, tenso y sin concesiones.",
  },
  {
    id: "act-010",
    tab: "friends",
    user: friendsMock[3],
    movieTitle: "Prisoners",
    movieYear: 2013,
    createdAt: "2026-04-07T21:00:00.000Z",
    interactionType: "rating",
    ratingValue: 4,
  },
  {
    id: "act-011",
    tab: "friends",
    user: friendsMock[4],
    movieTitle: "Dune",
    movieYear: 2021,
    createdAt: "2026-04-06T19:10:00.000Z",
    interactionType: "comment",
    commentText: "Escala visual gigantesca.",
  },
  {
    id: "act-012",
    tab: "friends",
    user: friendsMock[0],
    movieTitle: "In the Mood for Love",
    movieYear: 2000,
    createdAt: "2026-04-05T12:40:00.000Z",
    interactionType: "like",
    likedCommentSnippet: "La atmósfera es pura poesía.",
  },
];
